-- CREATE A DATABASE 
create database office ;

-- SWITCH A DATABASE
use office;

 -- CREATE A TABLE
create table officeboy(
EMP_ID int NOT NULL AUTO_INCREMENT primary key,
EMP_NAME VARCHAR(30) NOT NULL,
DOJ DATE NOT NULL,
AGE INT NOT NULL,
CITY VARCHAR (50) NOT NULL,
SALARY DECIMAL(15,3) NOT NULL);

SELECT * FROM OFFICEBOY;

-- INSERT DATA

INSERT INTO OFFICEBOY(EMP_NAME,DOJ,AGE,CITY,SALARY)
VALUES('AADVIK','2000-5-4',40,'MUMBAI', '50000');

INSERT INTO OFFICEBOY(EMP_NAME,DOJ,AGE,CITY,SALARY)
VALUES('SAVITA','2000-5-4',40,'GOA', '60000');

INSERT INTO OFFICEBOY(EMP_NAME,DOJ,AGE,CITY,SALARY)
VALUES('SHEETAL','2005-6-3',36,'MUMBAI', '50000');

INSERT INTO OFFICEBOY(EMP_NAME,DOJ,AGE,CITY,SALARY)
VALUES('SHAYAM','2010-4-2',32,'GUJRAT', '40000');

INSERT INTO OFFICEBOY(EMP_NAME,DOJ,AGE,CITY,SALARY)
VALUES('RAMA','2012-6-4',27,'PUNE', '60000');

INSERT INTO OFFICEBOY(EMP_NAME,DOJ,AGE,CITY,SALARY)
VALUES('RAMAN','2000-5-4',40,'MUMBAI', '50000');

INSERT INTO OFFICEBOY(EMP_NAME,DOJ,AGE,CITY,SALARY)
VALUES('SHALU','2001-1-1',25,'BHOPAL', '70000');

INSERT INTO OFFICEBOY(EMP_NAME,DOJ,AGE,CITY,SALARY)
VALUES('ABHI','2003-5-8',23,'JAIPUR', '65000');

INSERT INTO OFFICEBOY(EMP_NAME,DOJ,AGE,CITY,SALARY)
VALUES('RATAN','2013-7-1',42,'BIHAR', '45000');

INSERT INTO OFFICEBOY(EMP_NAME,DOJ,AGE,CITY,SALARY)
VALUES('ADARSH','2011-7-4',40,'JAIPUR', '57000');

INSERT INTO OFFICEBOY(EMP_NAME,DOJ,AGE,CITY,SALARY)
VALUES('VIKASH','2020-8-4',35,'GOA', '55000');

INSERT INTO OFFICEBOY(EMP_NAME,DOJ,AGE,CITY,SALARY)
VALUES('ROHAN','2000-8-6',40,'ASSAM', '70000');

INSERT INTO OFFICEBOY(EMP_NAME,DOJ,AGE,CITY,SALARY)
VALUES('RISHI','2001-5-4',60,'MADURAI', '80000');

INSERT INTO OFFICEBOY(EMP_NAME,DOJ,AGE,CITY,SALARY)
VALUES('ROHIT','2010-4-4',50,'JAIPUR', '45000');


SELECT * FROM OFFICEBOY;

-- UPDATE DATA
UPDATE OFFICEBOY 
SET EMP_NAME = 'RAM'
WHERE EMP_ID = 5;

UPDATE OFFICEBOY 
SET EMP_NAME = 'KRISHNA'
WHERE EMP_ID = 4;

UPDATE OFFICEBOY 
SET EMP_NAME = 'RONNI'
WHERE EMP_ID = 12;

-- UPDATE SALARY
UPDATE OFFICEBOY 
SET SALARY = 85000
WHERE EMP_ID = 5;


UPDATE OFFICEBOY 
SET SALARY = 90000
WHERE EMP_ID = 8;


-- DELETE FROM TABLE

DELETE FROM OFFICEBOY 
WHERE EMP_ID = 3;

-- USIING OPERATOR AND / OR
SELECT EMP_ID , EMP_NAME 
FROM OFFICEBOY
WHERE SALARY = 50000 AND AGE >30;
	 
SELECT EMP_ID , EMP_NAME 
FROM OFFICEBOY
WHERE CITY = 'JAIPUR' AND SALARY > 50000;
	 

SELECT EMP_ID , EMP_NAME ,CITY ,AGE
FROM OFFICEBOY
WHERE CITY = 'MUMBAI' OR SALARY > 40000 OR AGE >30;
	 
-- USING  NOT ,  LIKE
SELECT EMP_ID , EMP_NAME ,CITY
FROM OFFICEBOY
WHERE NOT CITY = 'JAIPUR' ;
	 
SELECT * FROM OFFICEBOY     
WHERE CITY LIKE 'G%';

SELECT * FROM OFFICEBOY     
WHERE EMP_NAME  LIKE 'R%';

-- END WITH 

SELECT * FROM OFFICEBOY     
WHERE CITY LIKE '%I';


SELECT * FROM OFFICEBOY     
WHERE EMP_NAME LIKE '%A';


-- NOT LIKE 

SELECT * FROM OFFICEBOY     
WHERE EMP_NAME NOT LIKE 'A%';

 -- OPERATOR IN 
SELECT * FROM OFFICEBOY     
WHERE CITY IN ('MUMBAI','GOA');

SELECT * FROM OFFICEBOY     
WHERE CITY NOT IN ('MUMBAI','GOA');

-- BETWEEN OPERATOR
SELECT * FROM OFFICEBOY     
WHERE SALARY BETWEEN 20000 AND 60000;

SELECT * FROM OFFICEBOY     
WHERE EMP_ID BETWEEN 2 AND 8;

SELECT * FROM OFFICEBOY     
WHERE DOJ BETWEEN '2000-5-4 'AND '2013-7-1';

SELECT * FROM OFFICEBOY     
ORDER BY EMP_NAME ,SALARY;

SELECT * FROM OFFICEBOY     
ORDER BY EMP_NAME DESC;

-- SQL FUNCTIONS
SELECT COUNT(EMP_NAME)
FROM OFFICEBOY;

SELECT SUM(SALARY)
FROM OFFICEBOY;

SELECT MIN(SALARY) AS LOWESTSALARY 
FROM OFFICEBOY;

SELECT AVG(SALARY)
FROM OFFICEBOY;




